# Site
name: "H4cker.it"
title: "H4cker.it"
description: "This blog is a space where I share my experiences and explore fascinating technologies I've encountered along the way. Join me as we navigate the world of cybersecurity and innovation together. Stay tuned for updates as we embark on this adventure!"
logo: 'assets/images/logo.gif'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/
email: dltmddyd645@naver.com

# Authors
authors:
  "SeungYong Lee":
    name: "SeungYong Lee"
    display_name: "SeungYong Lee"
    avatar: 'assets/images/avatar.png'
    email: "dltmddyd645@naver.com"
    web: "http://github.com/security-development"
    description: "
    I'm Seungyong Lee. I joined the AppSuit team at Stealien, a cybersecurity company based in South Korea, on September 27, 2022, where I conducted Android security research.
    As of January 1, 2025, I became a member of the Red Team, working alongside talented hackers to embrace challenging missions, including APT simulations and 0-day/1-day vulnerability research and development.<br/><br/>

    This blog is a space where I share my hands-on experiences and explore the fascinating technologies Iâ€™ve encountered.
    Join me in navigating the ever-evolving world of cybersecurity and innovation.
    "


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
